server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: marcas-relojes
          uri: lb://marcas-relojes
          predicates:
          - Path=/marcas/**
        - id: justificativos
          uri: lb://justificativos
          predicates:
          - Path=/justificativos/**
        - id: horas-extras
          uri: lb://horas-extras
          predicates:
          - Path=/horas_extra